version: '2'
services:
  web:
    build: .
    ports:
    - "5000:5000"

  s3:
    image: lphoward/fake-s3
    ports:
    - "4569:4569"

  dynamodb:
    image: cnadiminti/dynamodb-local
    ports:
    - "8000:8000"
    volumes:
    - db-data:/var/lib/dynamodb/data


volumes:
  db-data:

    #environment:

      #POSTGRES_USER: "flaskapp"
      #POSTGRES_PASSWORD: "hunter2"
